/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gasolinera;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class VentanaEstacion extends javax.swing.JFrame {

    private String cedula;
        private String cedulaEmpleadoActual; // Variable para almacenar la cédula


    /**
     * Creates new form VentanaEstacion_
     */
    public VentanaEstacion() {
        initComponents();

    }
        public String getCedulaEmpleado() {
        return cedulaEmpleadoActual;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloEstacion = new javax.swing.JLabel();
        btnEstacionCentral = new javax.swing.JButton();
        btnEstacionSur = new javax.swing.JButton();
        btnEstacionNorte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTituloEstacion.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        lblTituloEstacion.setText("Seleccion de Areas de Trabajo");

        btnEstacionCentral.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnEstacionCentral.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\OneDrive\\Escritorio\\imagenes\\surtidor.png")); // NOI18N
        btnEstacionCentral.setText("Estación Central");
        btnEstacionCentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstacionCentralActionPerformed(evt);
            }
        });

        btnEstacionSur.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnEstacionSur.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\OneDrive\\Escritorio\\imagenes\\surtidor.png")); // NOI18N
        btnEstacionSur.setText("Estación Sur");
        btnEstacionSur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstacionSurActionPerformed(evt);
            }
        });

        btnEstacionNorte.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnEstacionNorte.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\OneDrive\\Escritorio\\imagenes\\surtidor.png")); // NOI18N
        btnEstacionNorte.setText("Estación Norte");
        btnEstacionNorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstacionNorteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTituloEstacion)
                    .addComponent(btnEstacionSur, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstacionCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstacionNorte, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblTituloEstacion)
                .addGap(18, 18, 18)
                .addComponent(btnEstacionNorte, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEstacionCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEstacionSur, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstacionCentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstacionCentralActionPerformed
        if (verificarCedula()) {
            abrirVentanaFacturas("Estacion Central");
        }
    }//GEN-LAST:event_btnEstacionCentralActionPerformed

    private void btnEstacionSurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstacionSurActionPerformed
        if (verificarCedula()) {
            abrirVentanaFacturas("Estacion Sur");
        }
    }//GEN-LAST:event_btnEstacionSurActionPerformed

    private void btnEstacionNorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstacionNorteActionPerformed
        if (verificarCedula()) {
            abrirVentanaFacturas("Estación Norte");
        }
    }//GEN-LAST:event_btnEstacionNorteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEstacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEstacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEstacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEstacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEstacion().setVisible(true);
            }
        });
    }

    private void abrirVentanaFacturas(String nombreEstacion) {
        VentanaFacturas fac = new VentanaFacturas(nombreEstacion, this.cedula);
        fac.setVisible(true);
        this.dispose(); // Cerrar la ventana actual
    }

    private boolean verificarCedula() {
        String inputCedula = JOptionPane.showInputDialog(this, "Ingrese la cédula a verificar:");

        if (inputCedula != null && !inputCedula.isEmpty()) {
            if (cedulaExiste(inputCedula.trim())) {
                this.cedula = inputCedula.trim();
                return true;
            } else {
                JOptionPane.showMessageDialog(this, "La cédula no existe. No puedes continuar.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar una cédula válida.");
        }
        return false;
    }

    private boolean cedulaExiste(String cedula) {
        try (BufferedReader br = new BufferedReader(new FileReader(new File("empleados.txt")))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] fields = line.split(",");
                if (fields.length > 0 && fields[0].trim().equals(cedula)) {
                    return true;
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return false;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstacionCentral;
    private javax.swing.JButton btnEstacionNorte;
    private javax.swing.JButton btnEstacionSur;
    private javax.swing.JLabel lblTituloEstacion;
    // End of variables declaration//GEN-END:variables
}
