/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gasolinera;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author USER
 */
public class VentanaFacturas extends javax.swing.JFrame {

    private String cedula; 
    private static final double PRECIO_POR_LITRO = 3.0; 
    
    
    
    public VentanaFacturas() {
        initComponents();
    }

    private void configurarSpinners() {
        SpinnerCantidadLitros.setModel(new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1));
        SpinnerCantidadLitros.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                actualizarTotalPrecio();
            }
        });
    }

    private void actualizarTotalPrecio() {
        int cantidadLitros = (int) SpinnerCantidadLitros.getValue();
        double totalPrecio = cantidadLitros * PRECIO_POR_LITRO;
        fieldTotalPrecio.setText(String.format("%.2f", totalPrecio));
    }
    
    public VentanaFacturas(String nombreEstacion, String cedula) {
        this.cedula = cedula; 
        initComponents(); 
        configurarSpinners();

        lblTituloFactura.setText(nombreEstacion + " - Cédula empleado: " + cedula); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloFactura = new javax.swing.JLabel();
        lblGasolina = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        ComboGasolina = new javax.swing.JComboBox<>();
        btnGenerarFactura = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SpinnerCantidadLitros = new javax.swing.JSpinner();
        fieldTotalPrecio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        formatPlaca = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTituloFactura.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloFactura.setText("Estacion");

        lblGasolina.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblGasolina.setText("Gasolina:");

        lblCantidad.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblCantidad.setText("Cantidad en Lt:");

        lblPlaca.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblPlaca.setText("Placa:");

        ComboGasolina.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ComboGasolina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Extra", "Super", "Diesel" }));

        btnGenerarFactura.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btnGenerarFactura.setText("Generar Factura");
        btnGenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarFacturaActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setText("Llenar Datos:");

        fieldTotalPrecio.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setText("Total");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        try {
            formatPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblTituloFactura)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnGenerarFactura)
                            .addGap(149, 149, 149)
                            .addComponent(btnCancelar))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCantidad)
                                .addComponent(lblGasolina)
                                .addComponent(jLabel2)
                                .addComponent(lblPlaca))
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SpinnerCantidadLitros, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                .addComponent(formatPlaca)
                                .addComponent(ComboGasolina, 0, 174, Short.MAX_VALUE)
                                .addComponent(fieldTotalPrecio))
                            .addGap(94, 94, 94))))
                .addGap(0, 90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblTituloFactura)
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPlaca)
                    .addComponent(formatPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGasolina)
                            .addComponent(ComboGasolina, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantidad)
                            .addComponent(SpinnerCantidadLitros, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(8, 8, 8))
                    .addComponent(fieldTotalPrecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerarFactura)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarFacturaActionPerformed

        generarFactura();

    String placa = formatPlaca.getText();
    String gasolina = (String) ComboGasolina.getSelectedItem();
    String cantidad = SpinnerCantidadLitros.getValue().toString();
    String total = fieldTotalPrecio.getText();

   
    Factura factura = new Factura(cedula);
    factura.setVisible(true);
    factura.actualizarCampos(placa, gasolina, cantidad, total, cantidad);

    
    limpiarCampos();
    }//GEN-LAST:event_btnGenerarFacturaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
limpiarCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
VentanaEstacion estacion = new VentanaEstacion();
estacion.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFacturas().setVisible(true);
            }
        });
    }

private void generarFactura() {

    String placa = formatPlaca.getText();
    String gasolina = (String) ComboGasolina.getSelectedItem();
    String cantidad = SpinnerCantidadLitros.getValue().toString();


    String titulo = lblTituloFactura.getText();
    String nombreEstacion = titulo.split("-")[0].trim(); 

    String factura = cedula + "," + nombreEstacion + "," + placa + "," + gasolina + "," + cantidad;

    guardarFacturaEnArchivo(factura);
}


    private void guardarFacturaEnArchivo(String factura) {
        try {
            File file = new File("facturas.txt");

            if (!file.exists()) {
                file.createNewFile();
            }

            FileWriter fw = new FileWriter(file.getAbsoluteFile(), true);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(factura);
            bw.newLine(); 
            bw.close();

            JOptionPane.showMessageDialog(this, "Factura generada y guardada");

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar la factura: " + e.getMessage());
        }
    }
    
    private void limpiarCampos() {
    formatPlaca.setText("");
    ComboGasolina.setSelectedIndex(0); 
    SpinnerCantidadLitros.setValue(0);
    fieldTotalPrecio.setText("");
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboGasolina;
    private javax.swing.JSpinner SpinnerCantidadLitros;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGenerarFactura;
    private javax.swing.JTextField fieldTotalPrecio;
    private javax.swing.JFormattedTextField formatPlaca;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblGasolina;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblTituloFactura;
    // End of variables declaration//GEN-END:variables
}
