/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProyectoGasolinera;

import java.awt.Image;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class VentanaEstacion extends javax.swing.JFrame {

    private ImageIcon imagen;
    private Icon icono;

    private String cedula;
    private String nombre;
    private String apellido;
    private Conexion conexion;

    public VentanaEstacion() {
        initComponents();

        this.setLocationRelativeTo(this);
        this.Escalar(lblLogo, "/C:/Users/USER/OneDrive/Escritorio/mockitt/visual/logo.png");
        this.Escalar(lbl1, "/C:/Users/USER/OneDrive/Escritorio/mockitt/visual/estacion.png");
        this.Escalar(lbl2, "/C:/Users/USER/OneDrive/Escritorio/mockitt/visual/estacion.png");
        this.Escalar(lbl3, "/C:/Users/USER/OneDrive/Escritorio/mockitt/visual/estacion.png");
        this.Escalar(lblVolver, "/C:/Users/USER/OneDrive/Escritorio/mockitt/visual/volver.png");

    }

    public VentanaEstacion(String cedula, String nombre, String apellido) {
        initComponents();

        // Asigna los datos recibidos a los campos correspondientes
        this.cedula = cedula;
        this.nombre = nombre;
        this.apellido = apellido;

        // Actualiza los campos en la interfaz gráfica
        fieldCedulaEmp.setText(this.cedula);
        fieldNombreEmp.setText(this.nombre);
        fieldApellidoEmp.setText(this.apellido);

        this.conexion = new Conexion();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblVolver = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnEstacionSur = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnEstacionCentral = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnEstacionNorte = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        fieldCedulaEmp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fieldNombreEmp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fieldApellidoEmp = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel1.setText("SELECCIONAR ESTACIONES");

        lblVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVolverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(lblVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 80));

        jPanel3.setBackground(new java.awt.Color(255, 153, 51));

        btnEstacionSur.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        btnEstacionSur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEstacionSur.setText("Estación Sur");
        btnEstacionSur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEstacionSurMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEstacionSur, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEstacionSur, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 270, 80));

        jPanel4.setBackground(new java.awt.Color(255, 153, 51));

        btnEstacionCentral.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        btnEstacionCentral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEstacionCentral.setText("Estación Central");
        btnEstacionCentral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEstacionCentralMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEstacionCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEstacionCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, 80));

        jPanel5.setBackground(new java.awt.Color(255, 153, 51));

        btnEstacionNorte.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        btnEstacionNorte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEstacionNorte.setText("Estación Norte");
        btnEstacionNorte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEstacionNorteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEstacionNorte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEstacionNorte, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 270, 80));
        jPanel1.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 60, 60));
        jPanel1.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 60, 60));
        jPanel1.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 60, 60));

        fieldCedulaEmp.setEditable(false);
        fieldCedulaEmp.setBorder(null);
        jPanel1.add(fieldCedulaEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 230, 40));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel5.setText("Cedula:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel6.setText("Nombre:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        fieldNombreEmp.setEditable(false);
        fieldNombreEmp.setBackground(new java.awt.Color(255, 255, 255));
        fieldNombreEmp.setBorder(null);
        jPanel1.add(fieldNombreEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 230, 40));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel7.setText("Apellido:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, -1));

        fieldApellidoEmp.setEditable(false);
        fieldApellidoEmp.setBackground(new java.awt.Color(255, 255, 255));
        fieldApellidoEmp.setBorder(null);
        jPanel1.add(fieldApellidoEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 230, 40));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 280, 250));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel8.setText("Datos:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseClicked
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblVolverMouseClicked

    private void btnEstacionNorteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstacionNorteMouseClicked
        // Obtener el nombre de la estación desde el texto del botón
        String numeroEstacion = btnEstacionNorte.getText();

        // Obtener la cédula del empleado desde el campo fieldCedulaEmp
        String cedulaEmpleado = fieldCedulaEmp.getText();

        // Llamar al método para guardar en la base de datos
        guardarEstacionEnBaseDeDatos(numeroEstacion, cedulaEmpleado);

    }//GEN-LAST:event_btnEstacionNorteMouseClicked

    private void btnEstacionCentralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstacionCentralMouseClicked
        // Obtener el nombre de la estación desde el texto del botón
        String numeroEstacion = btnEstacionNorte.getText();

        // Obtener la cédula del empleado desde el campo fieldCedulaEmp
        String cedulaEmpleado = fieldCedulaEmp.getText();

        // Llamar al método para guardar en la base de datos
        guardarEstacionEnBaseDeDatos(numeroEstacion, cedulaEmpleado);

    }//GEN-LAST:event_btnEstacionCentralMouseClicked

    private void btnEstacionSurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstacionSurMouseClicked
        // Obtener el nombre de la estación desde el texto del botón
        String numeroEstacion = btnEstacionNorte.getText();

        // Obtener la cédula del empleado desde el campo fieldCedulaEmp
        String cedulaEmpleado = fieldCedulaEmp.getText();

        // Llamar al método para guardar en la base de datos
        guardarEstacionEnBaseDeDatos(numeroEstacion, cedulaEmpleado);

    }//GEN-LAST:event_btnEstacionSurMouseClicked

    private void guardarEstacionEnBaseDeDatos(String numeroEstacion, String cedulaEmpleado) {
        try {
            conexion.conectar();

            // Verificar si el empleado existe en la tabla Empleados
            String queryBuscarEmpleado = "SELECT EmpleadoID FROM Empleados WHERE Cedula = ?";
            PreparedStatement pstBuscarEmpleado = conexion.conn.prepareStatement(queryBuscarEmpleado);
            pstBuscarEmpleado.setString(1, cedulaEmpleado);

            ResultSet rs = pstBuscarEmpleado.executeQuery();

            if (rs.next()) {
                // Obtener el EmpleadoID existente
                int empleadoID = rs.getInt("EmpleadoID");

                // Consulta SQL para insertar datos en la tabla Estaciones
                String queryInsertEstacion = "INSERT INTO Estaciones (NumeroEstacion, fecha_ingreso, EmpleadoID) VALUES (?, NOW(), ?)";

                // Preparar la declaración SQL
                PreparedStatement pstInsertEstacion = conexion.conn.prepareStatement(queryInsertEstacion);
                pstInsertEstacion.setString(1, numeroEstacion);
                pstInsertEstacion.setInt(2, empleadoID);

                // Ejecutar la consulta
                int resultado = pstInsertEstacion.executeUpdate();

                // Verificar si la inserción fue exitosa
                if (resultado > 0) {
                    System.out.println("Estación registrada correctamente.");
                    Facturas factura = new Facturas();
                    factura.setVisible(true);
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(this, "Error al registrar la estación.", "Error", JOptionPane.ERROR_MESSAGE);
                }

                // Cerrar la declaración
                pstInsertEstacion.close();
            } else {
                JOptionPane.showMessageDialog(this, "El empleado con la cédula " + cedulaEmpleado + " no existe.", "Error", JOptionPane.ERROR_MESSAGE);
            }

            // Cerrar la declaración de búsqueda
            pstBuscarEmpleado.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error en la conexión con la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Desconectar siempre después de usar la conexión
            conexion.desconectar();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEstacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEstacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEstacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEstacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEstacion().setVisible(true);
            }
        });
    }

    private void Escalar(JLabel lbl, String ruta) {
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_DEFAULT));
        lbl.setIcon(this.icono);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnEstacionCentral;
    private javax.swing.JLabel btnEstacionNorte;
    private javax.swing.JLabel btnEstacionSur;
    private javax.swing.JTextField fieldApellidoEmp;
    private javax.swing.JTextField fieldCedulaEmp;
    private javax.swing.JTextField fieldNombreEmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblVolver;
    // End of variables declaration//GEN-END:variables
}
